- hosts: servers
  become: true
  roles:
    - system
    - geerlingguy.docker
    - role: traefik
      vars:
        service_cfg: "{{ traefik }}"
    - role: watchtower
      vars:
        service_cfg: "{{ watchtower }}"
    - role: autoheal
      vars:
        service_cfg: "{{ autoheal }}"
    - role: portainer
      vars:
        service_cfg: "{{ portainer }}"