- ansible.builtin.import_role:
    name: compose_hull
  vars:
    service_defaults:
      name: nodered
      port: 1880
      traefik: true
      external: false
      watchtower: true
      autoheal: true