- name: Build Traefik rule
  ansible.builtin.include_role:
    name: compose_hull
    tasks_from: traefik_middleware_builder
  with_items:
    - "{{ middleware_builder_config }}"
  loop_control:
    loop_var: middleware_builder_config

- name: "Set the rule String for Traefik to {{ traefik_middleware_list }}"
  ansible.builtin.set_fact:
    "{{ middleware_builder_config.name }}_middleware_list": "{{ traefik_middleware_list }}"
    "{{ middleware_builder_config.name }}_middleware_config_lines": "{{ traefik_middleware_config_lines }}"